version: '3.9'

services:

  pds:
    build:
      context: .
      dockerfile: Dockerfile
    hostname: bskypds
    networks:
      - traefik
    environment:
      PDS_HOSTNAME: example.com
      PDS_ADMIN_PASSWORD:
      PDS_JWT_SECRET:
      PDS_PLC_ROTATION_KEY_K256_PRIVATE_KEY_HEX:
      PDS_BLOBSTORE_DISK_LOCATION: /pds/blocks
      EUID: 0
      PDS_DATA_DIRECTORY: /pds
      PDS_BLOB_UPLOAD_LIMIT: 52428800
      PDS_BSKY_APP_VIEW_DID: did:web:api.bsky.app
      PDS_BSKY_APP_VIEW_URL: https://api.bsky.app
      PDS_CRAWLERS: https://bsky.network
      PDS_DID_PLC_URL: https://plc.directory
      PDS_REPORT_SERVICE_DID: did:plc:ar7c4by46qjdydhdevvrndac
      PDS_REPORT_SERVICE_URL: https://mod.bsky.app
    volumes:
      - data:/pds
    deploy:
      labels:
        traefik.enable: "true"
        traefik.docker.network: traefik
        traefik.wss.protocol: https
        traefik.http.services.bskypds.loadbalancer.server.port: 3000
        traefik.http.routers.bskypds.entrypoints: websecure
        traefik.http.routers.bskypds.rule: (HostRegexp(`^.+\.example\.com$$`) || Host(`example.com`)) && PathPrefix(`/xrpc`)
        traefik.http.routers.bskypds.tls.certresolver: cloudflare
        traefik.http.routers.bskypds.tls.domains[0].main: example.com
        traefik.http.routers.bskypds.tls.domains[0].sans: "*.example.com"
        traefik.http.routers.bskypds.priority: 1


volumes:
  data:

networks:
  traefik:
    name: traefik
    external: true

